services:
  # server:
  #   build: ./auth
  #   volumes:
  #     - ./auth:/app
  #   ports:
  #     - '2555:3000'
  #   env_file:
  #     - ./envs/auth.env

  mysql-expense:
    image: mysql:8.0
    container_name: mysql-expense
    environment:
      DATABASE_URL: mysql://root:root@mysql-expense:3306/expense
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3309:3306'
    networks:
      - expense-network
    volumes:
      - mysql-expense-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  expense:
    build: ./expense
    container_name: expense-container
    volumes:
      - ./expense:/app
    ports:
      - '3003:3003'
    env_file:
      - ./envs/expense.env
    depends_on:
      mysql-expense:
        condition: service_healthy
    networks:
      - expense-network

  mysql-financialgoal:
    image: mysql:8.0
    container_name: mysql-financialgoal
    environment:
      DATABASE_URL: mysql://root:root@mysql-financialgoal:3306/financialgoal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3307:3306'
    networks:
      - financialgoal-network
    volumes:
      - mysql-financialgoal-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  financialgoal:
    build: ./financialGoal
    container_name: financialgoal-container
    volumes:
      - ./financialGoal:/app
    ports:
      - '3001:3001'
    env_file:
      - ./envs/financialGoal.env
    depends_on:
      mysql-financialgoal:
        condition: service_healthy
    networks:
      - financialgoal-network

  mysql-paymentmethod:
    image: mysql:8.0
    container_name: mysql-paymentmethod
    environment:
      DATABASE_URL: mysql://root:root@mysql-paymentmethod:3306/paymentmethod
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3308:3306'
    networks:
      - paymentmethod-network
    volumes:
      - mysql-paymentmethod-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  paymentmethod:
    build: ./paymentMethod
    container_name: paymentmethod-container
    volumes:
      - ./paymentMethod:/app
    ports:
      - '3002:3002'
    env_file:
      - ./envs/paymentMethod.env
    depends_on:
      mysql-paymentmethod:
        condition: service_healthy
    networks:
      - paymentmethod-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    volumes:
      - ./api-gateway:/app
    ports:
      - '3000:3000'
    networks:
      - expense-network
      - financialgoal-network
      - paymentmethod-network

networks:
  expense-network:
    driver: bridge
  financialgoal-network:
    driver: bridge
  paymentmethod-network:
    driver: bridge

volumes:
  mysql-expense-data:
    driver: local
  mysql-financialgoal-data:
    driver: local
  mysql-paymentmethod-data:
    driver: local
