services:

  email-listener:
    build: ./email-listener
    container_name: email-listener
    volumes:
      - ./email-listener:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./envs/emailListener.env
    networks:
      - email-listener-network
  
  mysql-category:
    image: mysql:8.0
    container_name: mysql-category
    environment:
      DATABASE_URL: mysql://root:root@mysql-category:3306/category
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3311:3306'
    networks:
      - category-network
    volumes:
      - mysql-category-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  category:
    build: ./category
    container_name: category-container
    volumes:
      - ./category:/app
      - /app/node_modules
    ports:
      - '3006:3006'
    env_file:
      - ./envs/category.env
    depends_on:
      mysql-category:
        condition: service_healthy
    networks:
      - category-network
      - api-gateway-network

  mysql-saving:
    image: mysql:8.0
    container_name: mysql-saving
    environment:
      DATABASE_URL: mysql://root:root@mysql-saving:3306/saving
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3310:3306'
    networks:
      - saving-network
    volumes:
      - mysql-saving-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  saving:
    build: ./saving
    container_name: saving-container
    volumes:
      - ./saving:/app
      - /app/node_modules
    ports:
      - '3005:3005'
    env_file:
      - ./envs/saving.env
    depends_on:
      mysql-saving:
        condition: service_healthy
    networks:
      - saving-network
      - api-gateway-network

  mysql-transaction:
    image: mysql:8.0
    container_name: mysql-transaction
    environment:
      DATABASE_URL: mysql://root:root@mysql-transaction:3306/transaction
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3309:3306'
    networks:
      - transaction-network
    volumes:
      - mysql-transaction-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  transaction:
    build: ./transaction
    container_name: transaction-container
    volumes:
      - ./transaction:/app
      - /app/node_modules
    ports:
      - '3003:3003'
    env_file:
      - ./envs/transaction.env
    depends_on:
      mysql-transaction:
        condition: service_healthy
    networks:
      - transaction-network
      - api-gateway-network

  mysql-financialgoal:
    image: mysql:8.0
    container_name: mysql-financialgoal
    environment:
      DATABASE_URL: mysql://root:root@mysql-financialgoal:3306/financialgoal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3307:3306'
    networks:
      - financialgoal-network
    volumes:
      - mysql-financialgoal-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  financialgoal:
    build: ./financialGoal
    container_name: financialgoal-container
    volumes:
      - ./financialGoal:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    env_file:
      - ./envs/financialGoal.env
    depends_on:
      mysql-financialgoal:
        condition: service_healthy
    networks:
      - financialgoal-network
      - api-gateway-network

  mysql-paymentmethod:
    image: mysql:8.0
    container_name: mysql-paymentmethod
    environment:
      DATABASE_URL: mysql://root:root@mysql-paymentmethod:3306/paymentmethod
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fintrack
    ports:
      - '3308:3306'
    networks:
      - paymentmethod-network
    volumes:
      - mysql-paymentmethod-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  paymentmethod:
    build: ./paymentMethod
    container_name: paymentmethod-container
    volumes:
      - ./paymentMethod:/app
      - /app/node_modules
    ports:
      - '3002:3002'
    env_file:
      - ./envs/paymentMethod.env
    depends_on:
      mysql-paymentmethod:
        condition: service_healthy
    networks:
      - paymentmethod-network
      - api-gateway-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    networks:
      - api-gateway-network
    env_file:
      - ./envs/apiGateway.env

  auth-service:
    build: ./auth-service
    ports:
      - '3004:3004'
    env_file:
      - ./envs/auth.env
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    networks:
      - auth-network
      - api-gateway-network

  mysql:
    image: mysql:8
    ports:
      - '3305:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_db
    volumes:
      - mysql-auth-data:/var/lib/mysql
    networks:
      - auth-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-auth-data:/var/lib/rabbitmq
    networks:
      - auth-network
      - email-listener-network
      - api-gateway-network
    mem_limit: 256m
    cpus: 0.5
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  api-gateway-network:
    driver: bridge
  email-listener-network:
    driver: bridge
  category-network:
    driver: bridge
  saving-network:
    driver: bridge
  transaction-network:
    driver: bridge
  financialgoal-network:
    driver: bridge
  paymentmethod-network:
    driver: bridge
  auth-network:
    driver: bridge

volumes:
  mysql-category-data:
    driver: local
  mysql-saving-data:
    driver: local
  mysql-transaction-data:
    driver: local
  mysql-financialgoal-data:
    driver: local
  mysql-paymentmethod-data:
    driver: local
  mysql-auth-data:
    driver: local
  rabbitmq-auth-data:
    driver: local
