FROM node:lts

# Set the working directory
WORKDIR /app

COPY . .

RUN npm install

EXPOSE 3002

CMD ["sh", "-c", "npx prisma migrate deploy && if [ \"$DEBUG\" = \"TRUE\" ]; then npm run swagger; else npm run start:watch; fi"]