FROM node:lts

# Set the working directory
WORKDIR /app

COPY . .

RUN npm install

EXPOSE 3003

CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && if [ \"$DEBUG\" = \"TRUE\" ]; then npm run swagger; else npm run start:watch; fi"]